remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

plugins:
  - jekyll-titles-from-headings

title: Nutrigression: Recipe Reviews and Nutrition Analysis ğŸ—ğŸ¥šğŸ¥œ
  
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
